# Timeout in seconds that Limine will use before automatically booting.
timeout: 0
editor_enabled: yes
graphics: yes
interface_resolution: 1024x768

# The entry name that will be displayed in the boot menu.
/FeatherOS
    protocol: limine
    path: boot():/kernel.elf
    kaslr: no
    resolution: 1024x768
